package tc._473_381_DIV2_250;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class CopyOfTheBestName {

	/**
	 * @param args
	 */
	
	public class Name implements Comparable<Name> {
		public String name;
		public int order;
		public int sum;
		@Override
		public int compareTo(Name a) {
			if(sum > a.sum)
				return -1;
			else if(sum<a.sum){
				return 1;
			}else{			
				if(a.order<order)
					return 1;
				else 
					return -1;
			}
		}
	}
	public String[] sort(String[] names) {
		List<String> namesWeight = new ArrayList<String>();// john 47
		List<Name> list = new ArrayList<Name>();		
		for (int i = 0; i < names.length; i++) {
			String value = names[i];
		
			if(value.equals("JOHN")){
				namesWeight.add(value);			
			}else{
				int temp = calculatevalue(value);
				Name n= new Name();
				n.name=names[i];
				n.sum=temp;
				n.order=i;
				list.add(n);
			}	
		}
		Collections.sort(list);
		for(Name n:list){
			namesWeight.add(n.name);
		}
		for(int i=0;i<names.length;i++){
			names[i]=namesWeight.get(i);
		}
		return names;
	}

	private int calculatevalue(String value) {
		int temp = 0;
		for (int j = 0; j < value.length(); j++) {
			temp += value.charAt(j) - 64;
		}
		return temp;
	}

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		CopyOfTheBestName name=new CopyOfTheBestName();
		String[] na={"LILOKJMQML", "LKIIQIKIIIOMPOIOQOQOORNKIK", "QNQIJMIONIKIMI", "PRRRNKQKIMIIIQMNIO", "IOKKMPMIRMMPIKM", "NIMMKOQNRJKIMIQKL", "MOKIQIOQIQKNQMQKRKQII", "PQRNIIQRMORMONOKIMPM", "LLMNKIOIMOQNNOIQQKMKRI", "QOQKINQQMNQIQO", "OQIROIMIIJQNKOJO", "NNMKIIKINIKIII", "NMOOMMKQIIIIKMOKNQNKIMQPNI", "KIJPIIMIQIMNIKIQOJII", "KIMIINOKKPRK", "MKNPNQIOOQLOJNOIOMNNIMNIRKQQ", "IOILNMPKOQIIIMIRII"};
		String[] s=name.sort(na);
		String[] r={"MKNPNQIOOQLOJNOIOMNNIMNIRKQQ", "NMOOMMKQIIIIKMOKNQNKIMQPNI", "LKIIQIKIIIOMPOIOQOQOORNKIK", "LLMNKIOIMOQNNOIQQKMKRI", "PQRNIIQRMORMONOKIMPM", "MOKIQIOQIQKNQMQKRKQII", "PRRRNKQKIMIIIQMNIO", "KIJPIIMIQIMNIKIQOJII", "IOILNMPKOQIIIMIRII", "NIMMKOQNRJKIMIQKL", "OQIROIMIIJQNKOJO", "QOQKINQQMNQIQO", "IOKKMPMIRMMPIKM", "QNQIJMIONIKIMI", "NNMKIIKINIKIII", "KIMIINOKKPRK", "LILOKJMQML"};
		for(int i=0;i<s.length;i++){
			System.out.println(r[i]+"  "+i);
			System.out.println(s[i]+"  ");		
		}
		System.out.println("----------------------------------");
		String[] next={"EAACEAD", "DGDEGADABDA", "DFACEFAFDGCDDADGDFCAAAFEACCBAEGAFAFADD", "DACGDABDABFADCBFDDABGGDAEACGABD", "CDABBEEEAD", "CBCBFDBFDBFBAGDBAAAABFGBGGDFFDE", "AABCBECFFAGACGABBGB", "AFFBDBABGGCEABBDCEBDBGABAACGEAG", "GAGAAAAAGFDBAGGEFDCCEFAAAEGGAACAAADBEGEEFBGADFE", "FCEEGAADDFCGGAABAACECFGBEAFEGAACDF", "DAGAGGCACBACGCBGFBBEFDECACCEBAGBBEGEBDE", "CDAADAGGGFCAFGEDFFAADAEAAAEBGAAAACBDCC", "DFBEAAGDGDDAEDACBDABDFFAAAE", "BCAEAGADBCGCGABECBEDDACCE", "BBGEFBGCGAAACEGDEAB", "BBGCADEAFC", "ABCAACGACAA", "EDGEEDCAC", "EEEDABFFEFAFBECDGFCCBFCCAEDCBEAAGABF", "EBFGEEFFACGEEGEEA", "GECADABBGAD", "CCDEACDAAAAEAGAADDG", "AFDAAFFABEEBDBECEAFDAAEFEBFBCDAFEAEFAACGBC", "AEFBGAABGAAFADGDCF", "ACBDGEAADFABGFFBCCDGEAECGFCBGCAAFCBAGCAACAGDCAGC", "ADGDDAAEAAGECFDBDFACGDGEAGDAGECFCAACBBEFBFFEAEDCAD", "DAEFCCADFAAEFAEBAFCCFBBFCEEFBCEACFBFGAGBBABADA", "BABACBAFEDCCCAGFDFFGFGCDFFDAECAAGEADAED", "BGBAGCCDAEGFEGADFABBGBF", "FABFGGACCAAAAGECDFBABADFAFCFDADBFADCEACBE", "EAAAABGGCECDCAB", "BFEBDEGFFDFGFCABAAABB", "BGDABEDA", "CBAFAAAEBGCABDAGFCAGAEGBA", "GFCDACDDEAFFBBFADFBACCAABCADBAFFDCCGBABE", "BAFDEDCAGCFABDBAAADECFEEFDEFGAAGF", "DAFDCGCFADEBEBFGAACAFGEFCDDAGCE", "GECGDGGEAEA", "FGFCDFCAGACFFFFFCAAAAFGEF", "BAFGAAECCDBACAAADBADEGAAGAABCFGAFAAAA", "FABCFGDGDCCADAABDFAEEEAAAFCGDAAABDGDAC", "BGAEDACAAFFCBFGAF", "DGCEAGCAABGECDFAECCEAFGAGAFDGFEDDGF", "CDBDAAFAAEGAGEFAGAAEGACDGCGBGEEAAEBFDFBE"};
		String[] sn=name.sort(next);
		String[] nextr={"ADGDDAAEAAGECFDBDFACGDGEAGDAGECFCAACBBEFBFFEAEDCAD", "GAGAAAAAGFDBAGGEFDCCEFAAAEGGAACAAADBEGEEFBGADFE", "ACBDGEAADFABGFFBCCDGEAECGFCBGCAAFCBAGCAACAGDCAGC", "DAEFCCADFAAEFAEBAFCCFBBFCEEFBCEACFBFGAGBBABADA", "CDBDAAFAAEGAGEFAGAAEGACDGCGBGEEAAEBFDFBE", "DGCEAGCAABGECDFAECCEAFGAGAFDGFEDDGF", "BABACBAFEDCCCAGFDFFGFGCDFFDAECAAGEADAED", "AFDAAFFABEEBDBECEAFDAAEFEBFBCDAFEAEFAACGBC", "DAGAGGCACBACGCBGFBBEFDECACCEBAGBBEGEBDE", "DFACEFAFDGCDDADGDFCAAAFEACCBAEGAFAFADD", "FABFGGACCAAAAGECDFBABADFAFCFDADBFADCEACBE", "EEEDABFFEFAFBECDGFCCBFCCAEDCBEAAGABF", "GFCDACDDEAFFBBFADFBACCAABCADBAFFDCCGBABE", "FCEEGAADDFCGGAABAACECFGBEAFEGAACDF", "FABCFGDGDCCADAABDFAEEEAAAFCGDAAABDGDAC", "CDAADAGGGFCAFGEDFFAADAEAAAEBGAAAACBDCC", "BAFDEDCAGCFABDBAAADECFEEFDEFGAAGF", "DAFDCGCFADEBEBFGAACAFGEFCDDAGCE", "CBCBFDBFDBFBAGDBAAAABFGBGGDFFDE", "FGFCDFCAGACFFFFFCAAAAFGEF", "AFFBDBABGGCEABBDCEBDBGABAACGEAG", "BAFGAAECCDBACAAADBADEGAAGAABCFGAFAAAA", "DACGDABDABFADCBFDDABGGDAEACGABD", "DFBEAAGDGDDAEDACBDABDFFAAAE", "BGBAGCCDAEGFEGADFABBGBF", "BCAEAGADBCGCGABECBEDDACCE", "EBFGEEFFACGEEGEEA", "CBAFAAAEBGCABDAGFCAGAEGBA", "BFEBDEGFFDFGFCABAAABB", "BBGEFBGCGAAACEGDEAB", "AEFBGAABGAAFADGDCF", "AABCBECFFAGACGABBGB", "BGAEDACAAFFCBFGAF", "CCDEACDAAAAEAGAADDG", "GECGDGGEAEA", "EAAAABGGCECDCAB", "DGDEGADABDA", "EDGEEDCAC", "GECADABBGAD", "BBGCADEAFC", "CDABBEEEAD", "BGDABEDA", "ABCAACGACAA", "EAACEAD"};
		for(int i=0;i<s.length;i++){
			System.out.println(nextr[i]+"  "+i);
			System.out.println(sn[i]+"  ");
			
		}
	}

}
